### ISSUE TITLE
shopware.conf ---> robots.txt 

### ISSUE THREAD

**Issue by Winzigweich** [bcremer/shopware-with-nginx#19] opened 2016-05-16 08:17 UTC
this entry works not with robots.txt --> error 404 with nginx.
## robots.txt support.

location = /robots.txt {
    log_not_found off;
    access_log off;
}

change it with...

location = /robots.txt {
    log_not_found off;
    access_log off;
    try_files $uri @shopware;
}

it works. ;-)

**Comment by larsbo** [comment] 2016-08-29 18:32
I can confirm that the `try_files` directive is necessary.

**Comment by xf-** [comment] 2016-11-16 22:51
@bcremer should be added since it is a nice core feature

**Comment by bcremer** [comment] 2016-11-18 06:28
Closed by #26.

**Closed by bcremer** 2016-11-18 06:28 UTC
